---
title: "Small Area Estimation"
author: "Katherine Noack"
date: "9 June 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("D:/Education/2015-2018 - Master of Data Science/2018-S1 - Data Science Professional Development 2/AustraliaKidneyDisease")

library(dplyr)
library(car)
library(multcompView)
library(lsmeans)
library(rcompanion)
library(boot)
library(MASS)
library(tableHTML)
library(htmlTable)

library(sp)
library(rgdal)
library(broom)
library(data.table)
library(leaflet)
library(tidyr)

library(sae) # small area estimation

library(Metrics)

# Import Census data
load("./Processed-Data/CensusData.RData")

# Import health survey data
load("./Survey-Data/SurveyData.RData")

```

```{r Process}

# Roll up to larger area - if R and VR, then R
censusIndigenous2011 <- censusIndigenous2011 %>% 
  mutate(InnerRegional=ifelse(City>0 & InnerRegional>0,0,InnerRegional),
         OuterRegional=ifelse(InnerRegional>0 & OuterRegional>0,0,OuterRegional),
         Remote=ifelse(OuterRegional>0 & Remote>0,0,Remote),
         VeryRemote=ifelse(Remote>0&VeryRemote>0,0,VeryRemote))

censusIndigenous2011 <- censusIndigenous2011 %>% 
  gather("Remoteness","value",3:8) %>% 
  filter(value>0)

censusIndigenous2016 <- censusIndigenous2016 %>% 
  mutate(InnerRegional=ifelse(City>0 & InnerRegional>0,0,InnerRegional),
         OuterRegional=ifelse(InnerRegional>0 & OuterRegional>0,0,OuterRegional),
         Remote=ifelse(OuterRegional>0 & Remote>0,0,Remote),
         VeryRemote=ifelse(Remote>0&VeryRemote>0,0,VeryRemote))

censusIndigenous2016 <- censusIndigenous2016 %>% 
  gather("Remoteness","value",3:8) %>% 
  filter(value>0)

# rename variables back to match polygons
censusIndigenous2011 <- censusIndigenous2011 %>% 
  mutate(State = case_when(State=="NSW" ~ "New South Wales",
                           State=="QLD" ~ "Queensland",
                           State=="VIC" ~ "Victoria",
                           State=="TAS" ~ "Tasmania",
                           State=="SA" ~ "South Australia",
                           State=="WA" ~ "Western Australia",
                           State=="NT"~"Northern Territory",
                           State=="ACT" ~ "Australian Capital Territory"),
         Remoteness = case_when(Remoteness=="City" ~ "Major Cities of Australia",
                                Remoteness=="InnerRegional" ~ "Inner Regional Australia",
                                Remoteness=="OuterRegional" ~ "Outer Regional Australia",
                                Remoteness=="Remote" ~ "Remote Australia",
                                Remoteness=="VeryRemote" ~ "Very Remote Australia"))

censusIndigenous2011$Geography <- paste0(censusIndigenous2011$State,"-",censusIndigenous2011$Remoteness)

censusIndigenous2016 <- censusIndigenous2016 %>% 
  mutate(State = case_when(State=="NSW" ~ "New South Wales",
                           State=="QLD" ~ "Queensland",
                           State=="VIC" ~ "Victoria",
                           State=="TAS" ~ "Tasmania",
                           State=="SA" ~ "South Australia",
                           State=="WA" ~ "Western Australia",
                           State=="NT"~"Northern Territory",
                           State=="ACT" ~ "Australian Capital Territory"),
         Remoteness = case_when(Remoteness=="City" ~ "Major Cities of Australia",
                                Remoteness=="InnerRegional" ~ "Inner Regional Australia",
                                Remoteness=="OuterRegional" ~ "Outer Regional Australia",
                                Remoteness=="Remote" ~ "Remote Australia",
                                Remoteness=="VeryRemote" ~ "Very Remote Australia"))

censusIndigenous2016$Geography <- paste0(censusIndigenous2016$State,"-",censusIndigenous2016$Remoteness)

# Export 2012/2013 Kidney Disease rate in survey
survey <- data.frame(State=survey_geo$State, Remoteness=survey_geo$Remoteness, Geography=survey_geo$Geography,
                     Prediction=(survey_geo$Kidney.Disease/survey_geo$Total)*100)
display <- txtRound(survey, 3)
write_tableHTML(tableHTML(display), file = './Survey-Data/2011_GEO_SURVEY.html')

rm(survey, display)

unique(censusIndigenous2011[c("State","Geography")])
#census2011 <- census[which(census$Year == "2011"),]
#unique(census2011[c("State","VeryRemote")])


```

# Health Survey Map

```{r Map}

  healthSurvey <- data.frame(Geography=survey_geo$Geography, 
                             Prediction=(survey_geo$Kidney.Disease/survey_geo$Total)*100)
  healthSurvey$Prediction[is.nan(healthSurvey$Prediction)] <- 0

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=healthSurvey, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = healthSurvey$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 

```


# Generalised Linear Model - Age

```{r Linear-Age}

# https://www.statmethods.net/stats/regression.html
# Regression for Count data: http://rcompanion.org/handbook/J_01.html
# Survey package: https://cran.r-project.org/web/packages/survey/survey.pdf

# Generalised linear model to predict kidney disease in Indigenous population
#   Regression for count data (generalised linear regression)
#   Generalised linear models are used when the dependent variable is count, binary, multinomial, etc.
glmFit <- glm(Kidney.Disease/Total ~ Age, data = survey_age)
glmFit$family # The family object used

# Diagnostics
anova(glmFit)
summary(glmFit)
Anova(glmFit, type="II", test="LR")

fitDiag <- glm.diag(glmFit)
glm.diag.plots(glmFit, fitDiag)

x = residuals(glmFit)
plotNormalHistogram(x)
  
qqnorm(residuals(glmFit), ylab="Sample Quantiles for residuals")
qqline(residuals(glmFit), col="red")

plot(fitted(glmFit), residuals(glmFit))

rm(fitDiag, x)

# Apply to 2011 Indigenous Census data - predicts kidney disease rate (Kidney Disease / Total)
  data <- censusIndigenous2011
  data$Age <- as.character(data$Age)
  data$Age[data$Age == "80-89 years" | data$Age == "90-99 years"] <- "75 or over" 
  
  prediction2011 <- predict(glmFit, data.frame(Age=data$Age))
  prediction2011 <- data.frame(Geography=data$Geography, Prediction=prediction2011*100)
  
  data$KidneyDisease <- (prediction2011$Prediction/100) * data$Count
  sum(data$KidneyDisease) # Number of Indigenous people with kidney disease
  sum(data$Count) # Number of Indigenous people in data
  (sum(data$KidneyDisease) / sum(data$Count)) * 100 # Percentage with kidney disease
    
  prediction2011 <- aggregate(Prediction ~ Geography , mean, data=prediction2011)
  
  display <- txtRound(prediction2011, 3)
  write_tableHTML(tableHTML(display), file = './2011-Census-Analysis/tables/2011_GLM_Age.html')
  
# Calculate RMSE
  prediction <- predict(glmFit, data.frame(Age=survey_age$Age))
  actual <- survey_age$Kidney.Disease/survey_age$Total
  rmse(actual, prediction)
  
# 2011 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2011, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2011$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 

# Apply to 2016 Census
  data <- censusIndigenous2016
  data$Age <- as.character(data$Age)
  data$Age[data$Age == "80-89 years" | data$Age == "90-99 years"] <- "75 or over" 
  
  prediction2016 <- predict(glmFit, data.frame(Age=data$Age))
  
  prediction2016 <- data.frame(Geography=data$Geography, Prediction=prediction2016*100)
  prediction2016 <- aggregate(Prediction ~ Geography , mean, data=prediction2016)
  
  display <- txtRound(prediction2016, 3)
  write_tableHTML(tableHTML(display), file = './2016-Census-Analysis/tables/2016_GLM_Age.html')
  
# 2016 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2016, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2016$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 
  
```

# Generalised Linear Model - Remoteness Area

```{r Linear-Remotness}

glmFit <- glm(Kidney.Disease/Total ~ State + Remoteness, data = survey_geo)
glmFit$family # The family object used

# Diagnostics
anova(glmFit)
summary(glmFit)
Anova(glmFit, type="II", test="LR")

fitDiag <- glm.diag(glmFit)
glm.diag.plots(glmFit, fitDiag)

x = residuals(glmFit)
plotNormalHistogram(x)
  
qqnorm(residuals(glmFit), ylab="Sample Quantiles for residuals")
qqline(residuals(glmFit), col="red")

plot(fitted(glmFit), residuals(glmFit))

rm(fitDiag, x)

# Apply to 2011 Indigenous Census data - predicts kidney disease rate (Kidney Disease / Total)
  data <- censusIndigenous2011
  #data$Remoteness[data$Remoteness == "Very Remote Australia"] <- 
  #  "Very Remote Australia, Migratory (does not feature in these data), No usual address"

  prediction2011 <- predict(glmFit, data.frame(State=data$State, Remoteness=data$Remoteness))
  prediction2011 <- data.frame(Geography=data$Geography, Prediction=prediction2011*100)
  
  data$KidneyDisease <- (prediction2011$Prediction/100) * data$Count
  sum(data$KidneyDisease, na.rm = TRUE) # Number of Indigenous people with kidney disease
  sum(data$Count) # Number of Indigenous people in data
  (sum(data$KidneyDisease, na.rm = TRUE) / sum(data$Count)) * 100 # Percentage with kidney disease
  
  prediction2011 <- aggregate(Prediction ~ Geography , mean, data=prediction2011)
  
  display <- txtRound(prediction2011, 3)
  write_tableHTML(tableHTML(display), file = './2011-Census-Analysis/tables/2011_GLM_Remoteness.html')
  
    
# Calculate RMSE
  prediction <- predict(glmFit, data.frame(State=survey_geo$State, Remoteness=survey_geo$Remoteness))
  actual <- survey_geo$Kidney.Disease/survey_geo$Total
  actual[is.nan(actual)] <- 0
  rmse(actual, prediction)

# 2011 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2011, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2011$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 

# Apply to 2016 Census
  data <- censusIndigenous2016
  #data$Remoteness[data$Remoteness == "Very Remote Australia"] <- 
  #  "Very Remote Australia, Migratory (does not feature in these data), No usual address"

  prediction2016 <- predict(glmFit, data.frame(State=data$State, Remoteness=data$Remoteness))
  
  prediction2016 <- data.frame(Geography=data$Geography, Prediction=prediction2016*100)
  prediction2016 <- aggregate(Prediction ~ Geography , mean, data=prediction2016)
  
  display <- txtRound(prediction2016, 3)
  write_tableHTML(tableHTML(display), file = './2016-Census-Analysis/tables/2016_GLM_Remoteness.html')
  
# 2016 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2016, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2016$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)")

```

# Generalised Linear Model - Income

```{r Linear-Income}

glmFit <- glm(Kidney.Disease/Total ~ incm, data = survey_incm)
glmFit$family # The family object used

# Diagnostics
anova(glmFit)
summary(glmFit)
Anova(glmFit, type="II", test="LR")

fitDiag <- glm.diag(glmFit)
glm.diag.plots(glmFit, fitDiag)

x = residuals(glmFit)
plotNormalHistogram(x)
  
qqnorm(residuals(glmFit), ylab="Sample Quantiles for residuals")
qqline(residuals(glmFit), col="red")

plot(fitted(glmFit), residuals(glmFit))

rm(fitDiag, step, x)

# Apply to 2011 Indigenous Census data - predicts kidney disease rate (Kidney Disease / Total)
  data <- censusIndigenous2011
  data$Income <- as.character(data$Income)
  data$Income[data$Income == "Negative income" | data$Income == "Not stated" | 
                data$Income == "Not applicable" | data$Income == "Nil income"] <- "Not known"
  
  prediction2011 <- predict(glmFit, data.frame(incm=data$Income))
  prediction2011 <- data.frame(Geography=data$Geography, Prediction=prediction2011*100)
  
  data$KidneyDisease <- (prediction2011$Prediction/100) * data$Count
  sum(data$KidneyDisease, na.rm = TRUE) # Number of Indigenous people with kidney disease
  sum(data$Count) # Number of Indigenous people in data
  (sum(data$KidneyDisease, na.rm = TRUE) / sum(data$Count)) * 100 # Percentage with kidney disease
  
  prediction2011 <- aggregate(Prediction ~ Geography , mean, data=prediction2011)
  
  display <- txtRound(prediction2011, 3)
  write_tableHTML(tableHTML(display), file = './2011-Census-Analysis/tables/2011_GLM_Income.html')

# Calculate RMSE
  prediction <- predict(glmFit, data.frame(incm=survey_incm$incm))
  actual <- survey_incm$Kidney.Disease/survey_incm$Total
  rmse(actual, prediction)
  
# 2011 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2011, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2011$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 

# Apply to 2016 Census
  data <- censusIndigenous2016
  data$Income <- as.character(data$Income)
  data$Income[data$Income == "Negative income" | data$Income == "Not stated" | 
                data$Income == "Not applicable" | data$Income == "Nil income"] <- "Not known"
  
  prediction2016 <- predict(glmFit, data.frame(incm=data$Income))
  
  prediction2016 <- data.frame(Geography=data$Geography, Prediction=prediction2016*100)
  prediction2016 <- aggregate(Prediction ~ Geography , mean, data=prediction2016)
  
  display <- txtRound(prediction2016, 3)
  write_tableHTML(tableHTML(display), file = './2016-Census-Analysis/tables/2016_GLM_Income.html')
  
# 2016 Map

  remote_poly = readOGR(path.expand("./Processed-Data/RemotenessAreaShapeFile/RA_2011_AUST.shp"), 
                        stringsAsFactors=FALSE)
  remote_poly@data$STE_RA = paste0(remote_poly@data$STE_NAME11,"-",remote_poly@data$RA_NAME11)
  
  # Join the CSV data to the shapefile:
  results_poly = merge(x=remote_poly, y=prediction2016, by.x="STE_RA",by.y="Geography")
  
  ## define a palette for the colour
  pal <- colorNumeric(palette = "YlOrRd",
                      domain = prediction2016$Prediction)
  #polygons
  leaflet(data=results_poly) %>%
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                opacity = 1.0, fillOpacity = 0.5,
                fillColor = ~pal(Prediction),
                highlightOptions = highlightOptions(color = "white", weight = 2,
                                                    bringToFront = TRUE)) %>%
    addLegend(position = "bottomleft", pal = pal, values = ~Prediction, title="Kidney Disease (percentage)") 

```

# Evaluation

```{r Evaluate}

# TODO: Compare models

```

